import Vue from 'vue'
import Vuex from 'vuex'
import axios from 'axios'

Vue.use(Vuex);

const getDefaultDogs = () => {
  return {
    dogs: [
      {
        name: 'Rocky',
        image: '1.jpeg',
        breed: 'Breed 1',
        registration: '1 Jun 2022',
        birth: '1 March 2020',
        last_update: '1 April 2022',
      },
      {
        name: 'Brad',
        image: '2.jpeg',
        breed: 'Breed 1',
        registration: '2 Jun 2022',
        birth: '2 March 2020',
        last_update: '2 April 2022',
      },
      {
        name: 'Chucky',
        image: '3.jpeg',
        breed: 'Breed 1',
        registration: '3 Jun 2022',
        birth: '3 March 2020',
        last_update: '3 April 2022',
      },
      {
        name: 'Lucky',
        image: '4.jpeg',
        breed: 'Breed 1',
        registration: '4 Jun 2022',
        birth: '4 March 2020',
        last_update: '4 April 2022',
      },
      {
        name: 'Princess',
        image: '5.jpeg',
        breed: 'Breed 2',
        registration: '5 Jun 2022',
        birth: '5 March 2020',
        last_update: '5 April 2022',
      },
      {
        name: 'Lucia',
        image: '6.jpeg',
        breed: 'Breed 2',
        registration: '6 Jun 2022',
        birth: '6 March 2020',
        last_update: '6 April 2022',
      },
      {
        name: 'Scar',
        image: '7.jpeg',
        breed: 'Breed 1',
        registration: '7 Jun 2022',
        birth: '7 March 2020',
        last_update: '7 April 2022',
      },
      {
        name: 'Gav',
        image: '8.jpeg',
        breed: 'Breed 1',
        registration: '8 Jun 2022',
        birth: '8 March 2020',
        last_update: '8 April 2022',
      },
      {
        name: 'Kelly',
        image: '9.jpeg',
        breed: 'Breed 2',
        registration: '9 Jun 2022',
        birth: '9 March 2020',
        last_update: '9 April 2022',
      },
      {
        name: 'Lucky',
        image: '10.jpeg',
        breed: 'Breed 1',
        registration: '10 Jun 2022',
        birth: '10 March 2020',
        last_update: '10 April 2022',
      },
      {
        name: 'Rocky',
        image: '1.jpeg',
        breed: 'Breed 1',
        registration: '1 Jun 2022',
        birth: '1 March 2020',
        last_update: '1 April 2022',
      },
      {
        name: 'Brad',
        image: '2.jpeg',
        breed: 'Breed 1',
        registration: '2 Jun 2022',
        birth: '2 March 2020',
        last_update: '2 April 2022',
      },
      {
        name: 'Chucky',
        image: '3.jpeg',
        breed: 'Breed 1',
        registration: '3 Jun 2022',
        birth: '3 March 2020',
        last_update: '3 April 2022',
      },
      {
        name: 'Lucky',
        image: '4.jpeg',
        breed: 'Breed 1',
        registration: '4 Jun 2022',
        birth: '4 March 2020',
        last_update: '4 April 2022',
      },
      {
        name: 'Princess',
        image: '5.jpeg',
        breed: 'Breed 2',
        registration: '5 Jun 2022',
        birth: '5 March 2020',
        last_update: '5 April 2022',
      },
      {
        name: 'Lucia',
        image: '6.jpeg',
        breed: 'Breed 2',
        registration: '6 Jun 2022',
        birth: '6 March 2020',
        last_update: '6 April 2022',
      },
      {
        name: 'Scar',
        image: '7.jpeg',
        breed: 'Breed 1',
        registration: '7 Jun 2022',
        birth: '7 March 2020',
        last_update: '7 April 2022',
      },
      {
        name: 'Gav',
        image: '8.jpeg',
        breed: 'Breed 1',
        registration: '8 Jun 2022',
        birth: '8 March 2020',
        last_update: '8 April 2022',
      },
      {
        name: 'Kelly',
        image: '9.jpeg',
        breed: 'Breed 2',
        registration: '9 Jun 2022',
        birth: '9 March 2020',
        last_update: '9 April 2022',
      },
      {
        name: 'Lucky',
        image: '10.jpeg',
        breed: 'Breed 1',
        registration: '10 Jun 2022',
        birth: '10 March 2020',
        last_update: '10 April 2022',
      },
      {
        name: 'Rocky',
        image: '1.jpeg',
        breed: 'Breed 1',
        registration: '1 Jun 2022',
        birth: '1 March 2020',
        last_update: '1 April 2022',
      },
      {
        name: 'Brad',
        image: '2.jpeg',
        breed: 'Breed 1',
        registration: '2 Jun 2022',
        birth: '2 March 2020',
        last_update: '2 April 2022',
      },
      {
        name: 'Chucky',
        image: '3.jpeg',
        breed: 'Breed 1',
        registration: '3 Jun 2022',
        birth: '3 March 2020',
        last_update: '3 April 2022',
      },
      {
        name: 'Lucky',
        image: '4.jpeg',
        breed: 'Breed 1',
        registration: '4 Jun 2022',
        birth: '4 March 2020',
        last_update: '4 April 2022',
      },
      {
        name: 'Princess',
        image: '5.jpeg',
        breed: 'Breed 2',
        registration: '5 Jun 2022',
        birth: '5 March 2020',
        last_update: '5 April 2022',
      },
      {
        name: 'Lucia',
        image: '6.jpeg',
        breed: 'Breed 2',
        registration: '6 Jun 2022',
        birth: '6 March 2020',
        last_update: '6 April 2022',
      },
      {
        name: 'Scar',
        image: '7.jpeg',
        breed: 'Breed 1',
        registration: '7 Jun 2022',
        birth: '7 March 2020',
        last_update: '7 April 2022',
      },
      {
        name: 'Gav',
        image: '8.jpeg',
        breed: 'Breed 1',
        registration: '8 Jun 2022',
        birth: '8 March 2020',
        last_update: '8 April 2022',
      },
      {
        name: 'Kelly',
        image: '9.jpeg',
        breed: 'Breed 2',
        registration: '9 Jun 2022',
        birth: '9 March 2020',
        last_update: '9 April 2022',
      },
      {
        name: 'Lucky',
        image: '10.jpeg',
        breed: 'Breed 1',
        registration: '10 Jun 2022',
        birth: '10 March 2020',
        last_update: '10 April 2022',
      },
      {
        name: 'Rocky',
        image: '1.jpeg',
        breed: 'Breed 1',
        registration: '1 Jun 2022',
        birth: '1 March 2020',
        last_update: '1 April 2022',
      },
      {
        name: 'Brad',
        image: '2.jpeg',
        breed: 'Breed 1',
        registration: '2 Jun 2022',
        birth: '2 March 2020',
        last_update: '2 April 2022',
      },
      {
        name: 'Chucky',
        image: '3.jpeg',
        breed: 'Breed 1',
        registration: '3 Jun 2022',
        birth: '3 March 2020',
        last_update: '3 April 2022',
      },
      {
        name: 'Lucky',
        image: '4.jpeg',
        breed: 'Breed 1',
        registration: '4 Jun 2022',
        birth: '4 March 2020',
        last_update: '4 April 2022',
      },
      {
        name: 'Princess',
        image: '5.jpeg',
        breed: 'Breed 2',
        registration: '5 Jun 2022',
        birth: '5 March 2020',
        last_update: '5 April 2022',
      },
      {
        name: 'Lucia',
        image: '6.jpeg',
        breed: 'Breed 2',
        registration: '6 Jun 2022',
        birth: '6 March 2020',
        last_update: '6 April 2022',
      },
      {
        name: 'Scar',
        image: '7.jpeg',
        breed: 'Breed 1',
        registration: '7 Jun 2022',
        birth: '7 March 2020',
        last_update: '7 April 2022',
      },
      {
        name: 'Gav',
        image: '8.jpeg',
        breed: 'Breed 1',
        registration: '8 Jun 2022',
        birth: '8 March 2020',
        last_update: '8 April 2022',
      },
      {
        name: 'Kelly',
        image: '9.jpeg',
        breed: 'Breed 2',
        registration: '9 Jun 2022',
        birth: '9 March 2020',
        last_update: '9 April 2022',
      },
      {
        name: 'Lucky',
        image: '10.jpeg',
        breed: 'Breed 1',
        registration: '10 Jun 2022',
        birth: '10 March 2020',
        last_update: '10 April 2022',
      },
      {
        name: 'Rocky',
        image: '1.jpeg',
        breed: 'Breed 1',
        registration: '1 Jun 2022',
        birth: '1 March 2020',
        last_update: '1 April 2022',
      },
      {
        name: 'Brad',
        image: '2.jpeg',
        breed: 'Breed 1',
        registration: '2 Jun 2022',
        birth: '2 March 2020',
        last_update: '2 April 2022',
      },
      {
        name: 'Chucky',
        image: '3.jpeg',
        breed: 'Breed 1',
        registration: '3 Jun 2022',
        birth: '3 March 2020',
        last_update: '3 April 2022',
      },
      {
        name: 'Lucky',
        image: '4.jpeg',
        breed: 'Breed 1',
        registration: '4 Jun 2022',
        birth: '4 March 2020',
        last_update: '4 April 2022',
      },
      {
        name: 'Princess',
        image: '5.jpeg',
        breed: 'Breed 2',
        registration: '5 Jun 2022',
        birth: '5 March 2020',
        last_update: '5 April 2022',
      },
      {
        name: 'Lucia',
        image: '6.jpeg',
        breed: 'Breed 2',
        registration: '6 Jun 2022',
        birth: '6 March 2020',
        last_update: '6 April 2022',
      },
      {
        name: 'Scar',
        image: '7.jpeg',
        breed: 'Breed 1',
        registration: '7 Jun 2022',
        birth: '7 March 2020',
        last_update: '7 April 2022',
      },
      {
        name: 'Gav',
        image: '8.jpeg',
        breed: 'Breed 1',
        registration: '8 Jun 2022',
        birth: '8 March 2020',
        last_update: '8 April 2022',
      },
      {
        name: 'Kelly',
        image: '9.jpeg',
        breed: 'Breed 2',
        registration: '9 Jun 2022',
        birth: '9 March 2020',
        last_update: '9 April 2022',
      },
      {
        name: 'Lucky',
        image: '10.jpeg',
        breed: 'Breed 1',
        registration: '10 Jun 2022',
        birth: '10 March 2020',
        last_update: '10 April 2022',
      },
      {
        name: 'Rocky',
        image: '1.jpeg',
        breed: 'Breed 1',
        registration: '1 Jun 2022',
        birth: '1 March 2020',
        last_update: '1 April 2022',
      },
      {
        name: 'Brad',
        image: '2.jpeg',
        breed: 'Breed 1',
        registration: '2 Jun 2022',
        birth: '2 March 2020',
        last_update: '2 April 2022',
      },
      {
        name: 'Chucky',
        image: '3.jpeg',
        breed: 'Breed 1',
        registration: '3 Jun 2022',
        birth: '3 March 2020',
        last_update: '3 April 2022',
      },
      {
        name: 'Lucky',
        image: '4.jpeg',
        breed: 'Breed 1',
        registration: '4 Jun 2022',
        birth: '4 March 2020',
        last_update: '4 April 2022',
      },
      {
        name: 'Princess',
        image: '5.jpeg',
        breed: 'Breed 2',
        registration: '5 Jun 2022',
        birth: '5 March 2020',
        last_update: '5 April 2022',
      },
      {
        name: 'Lucia',
        image: '6.jpeg',
        breed: 'Breed 2',
        registration: '6 Jun 2022',
        birth: '6 March 2020',
        last_update: '6 April 2022',
      },
      {
        name: 'Scar',
        image: '7.jpeg',
        breed: 'Breed 1',
        registration: '7 Jun 2022',
        birth: '7 March 2020',
        last_update: '7 April 2022',
      },
      {
        name: 'Gav',
        image: '8.jpeg',
        breed: 'Breed 1',
        registration: '8 Jun 2022',
        birth: '8 March 2020',
        last_update: '8 April 2022',
      },
      {
        name: 'Kelly',
        image: '9.jpeg',
        breed: 'Breed 2',
        registration: '9 Jun 2022',
        birth: '9 March 2020',
        last_update: '9 April 2022',
      },
      {
        name: 'Lucky',
        image: '10.jpeg',
        breed: 'Breed 1',
        registration: '10 Jun 2022',
        birth: '10 March 2020',
        last_update: '10 April 2022',
      },
      {
        name: 'Rocky',
        image: '1.jpeg',
        breed: 'Breed 1',
        registration: '1 Jun 2022',
        birth: '1 March 2020',
        last_update: '1 April 2022',
      },
      {
        name: 'Brad',
        image: '2.jpeg',
        breed: 'Breed 1',
        registration: '2 Jun 2022',
        birth: '2 March 2020',
        last_update: '2 April 2022',
      },
      {
        name: 'Chucky',
        image: '3.jpeg',
        breed: 'Breed 1',
        registration: '3 Jun 2022',
        birth: '3 March 2020',
        last_update: '3 April 2022',
      },
      {
        name: 'Lucky',
        image: '4.jpeg',
        breed: 'Breed 1',
        registration: '4 Jun 2022',
        birth: '4 March 2020',
        last_update: '4 April 2022',
      },
      {
        name: 'Princess',
        image: '5.jpeg',
        breed: 'Breed 2',
        registration: '5 Jun 2022',
        birth: '5 March 2020',
        last_update: '5 April 2022',
      },
      {
        name: 'Lucia',
        image: '6.jpeg',
        breed: 'Breed 2',
        registration: '6 Jun 2022',
        birth: '6 March 2020',
        last_update: '6 April 2022',
      },
      {
        name: 'Scar',
        image: '7.jpeg',
        breed: 'Breed 1',
        registration: '7 Jun 2022',
        birth: '7 March 2020',
        last_update: '7 April 2022',
      },
      {
        name: 'Gav',
        image: '8.jpeg',
        breed: 'Breed 1',
        registration: '8 Jun 2022',
        birth: '8 March 2020',
        last_update: '8 April 2022',
      },
      {
        name: 'Kelly',
        image: '9.jpeg',
        breed: 'Breed 2',
        registration: '9 Jun 2022',
        birth: '9 March 2020',
        last_update: '9 April 2022',
      },
      {
        name: 'Lucky',
        image: '10.jpeg',
        breed: 'Breed 1',
        registration: '10 Jun 2022',
        birth: '10 March 2020',
        last_update: '10 April 2022',
      },
    ],
  };
};

const getDefaultTimelines = () => {
  return {
    timelines: [
      {
        name: "Rocky",
        message: 'Tom committed',
        date: '2018/3/1',
        time: '17:46'
      },
      {
        name: "Riscky",
        message: 'Tom committed',
        date: '2019/7/3',
        time: '11:46'
      },
      {
        name: "Lucky",
        message: 'Tom committed',
        date: '2020/4/30',
        time: '05:46'
      },
      {
        name: "Lucy",
        message: 'Tom committed',
        date: '2021/9/25',
        time: '21:46'
      },
      {
        name: "Spot",
        message: 'Tom committed',
        date: '2022/4/17',
        time: '10:46'
      },
      {
        name: "Chucky",
        message: 'Tom committed',
        date: '2023/1/17',
        time: '03:46'
      },
    ]
  };
};

const dogs = {
  state: {
    dogs: [],
    timelines: []
  },

  actions: {
    async fetchDogs({ commit }) {
      try {
        const response = await axios.get('https://api.thedogapi.com/v1/dogs');
        commit('SET_DOGS', response.data);
      } catch (error) {
        commit("SET_DEFAULT_DOGS");
        commit("SET_DEFAULT_TIMELINES");
      }
    },
  },

  mutations: {
    SET_DOGS(state, dogs) {
      state.dogs = dogs;
    },
    SET_DEFAULT_DOGS(state) {
      Object.assign(state, getDefaultDogs());
    },
    SET_DEFAULT_TIMELINES(state) {
      Object.assign(state, getDefaultTimelines());
    },
  }
}

export default dogs;
